import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/Store/ReduxProvider";
import Header from "@/components/Header/Header";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SkyProFitness",
  description: "Generated by create Fitness app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={roboto.className}>
      <ReduxProvider>
        <body className={`${roboto.variable}`}>
          <Header />
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
